language: python
python:
  - 3.8
install:
  - pip install -q pipenv codecov
  - pipenv sync --dev
script:
  - pipenv run flake8 .
  - pipenv run pytest --cov=pypro
  - cp contrib/env-sample .env

after_success:
  - pipenv run codecov
