# Generated by Django 3.0.6 on 2020-05-26 23:17

from django.db import migrations
import pypro.base.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', pypro.base.models.UserManager()),
            ],
        ),
    ]
